language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --exclude-group integration --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
